inherit_from:
  - https://potpourri.hausgold.de/config/rubocop.yml
  - https://potpourri.hausgold.de/config/rubocop-gem.yml

inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true
  TargetRubyVersion: 3.3
  TargetRailsVersion: 8.0
  Exclude:
    - bin/**/*
    - vendor/**/*
    - build/**/*
    - gemfiles/**/*
    - spec/fixtures/files/**/*

# It's a deliberate idiom in RSpec.
# See: https://github.com/bbatsov/rubocop/issues/4222
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

# Disable regular Rails spec paths.
Rails/FilePath:
  Enabled: false

# Because +enqueued_jobs+ is a method not a memoized variable,
# so when first evaluated it won't change.
RSpec/ExpectChange:
  Enabled: false

# Because we support Rails applications as well as gems and non-Rails
# applications, therefore the +:environment+ task is not always present
Rails/RakeEnvironment:
  Enabled: false
